Homework 8

Jonathon Vasilak

Problem 1

In [0]:
import math
side_1 = 10
side_2 = 15


hypotenuse = math.sqrt(side_1*side_1+side_2*side_2)
angle_1 = math.acos((side_1/hypotenuse))*(180/math.pi)
angle_2 = math.acos((side_2/hypotenuse))*(180/math.pi)
print('The hypotenuse of the triangle is ', hypotenuse,'.')
print('The two acute angles are ', angle_1, ' and ', angle_2, ' degrees.')

The hypotenuse of the triangle is  18.027756377319946 .
The two acute angles are  56.309932474020215  and  33.690067525979785  degrees.

Problem 2

In [0]:
N = input('How many Fibonacci numbers would you like to see the sum of?')
N = int(N)
fibonaci = [0]*N
fibonaci[0] = 0
fibonaci[1] = 1
fibonaci_sum = 1 
for i in range(2,N,1):
  fibonaci[i] = fibonaci[i-1]+fibonaci[i-2]
  fibonaci_sum = fibonaci_sum + fibonaci[i]

print(fibonaci)
print('The sum of the first ', N, 'fiboaci numbers is ', fibonaci_sum, '.')

How many Fibonacci numbers would you like to see the sum of?10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
The sum of the first  10 fiboaci numbers is  88 .

Problem 3

In [0]:
N = input('How many numbers would you like to process? ')
N = int(N)
number = [0]*N
for i in range(0,N,1):
  number[i] = input('Enter number: ')

max_val = number[0]
index = 0
for i in range(1,N,1):
  if number[i] > max_val:
    max_val = number[i]
    index = i

print('The maximum value is ', max_val, '.')
print('The value is saved in index #', index, '.')

How many numbers would you like to process? 4
Enter number: 4
Enter number: 56
Enter number: 2
Enter number: 1
The maximum value is  56 .
The value is saved in index # 1 .

Problem 4

In [7]:
def c2f(Ctemp):
  Ftemp = (Ctemp*1.8)+32
  return Ftemp

print('T(C)  T(F)')
for i in range(0,9,2):
  C = i
  F = c2f(C)
  print(C,'   ', F)

T(C)  T(F)
0     32.0
2     35.6
4     39.2
6     42.8
8     46.4

Problem 5

In [21]:
years = 30
interest_rate = 0.08
initial_balance = 1000
Balance = [0]*years
Balance[0] = initial_balance

for i in range(1,years,1):
  Balance[i] = Balance[i-1]+interest_rate*Balance[i-1]
Balance[years-1] = round(Balance[years-1], 2)
print('The total balance at the beginning of year ', years, ' is ', Balance[years-1],  ' dollars.')

The total balance at the beginning of year  30  is  9317.27  dollars.